"use client";

import { use, useEffect, useState } from "react";
import type { StoredLead } from "@helix/core";

function tierColor(tier: StoredLead["tier"]) {
  if (tier === "hot") return "#059669";
  if (tier === "warm") return "#d97706";
  return "#dc2626";
}

export default function LeadReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [lead, setLead] = useState<StoredLead | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    document.body.setAttribute("data-report-print", "1");
    return () => document.body.removeAttribute("data-report-print");
  }, []);

  useEffect(() => {
    fetch(`/api/leads/${id}`)
      .then((r) => r.json())
      .then((d: { lead?: StoredLead; error?: string }) => {
        if (d.error || !d.lead) {
          setError(d.error ?? "Lead not found");
          return;
        }
        setLead(d.lead);
      })
      .catch(() => setError("Could not load this lead."));
  }, [id]);

  if (error) {
    return (
      <div className="mx-auto max-w-2xl px-6 py-12 text-center text-slate-400">
        <p>{error}</p>
      </div>
    );
  }
  if (!lead) {
    return <div className="mx-auto max-w-2xl px-6 py-12 text-center text-slate-500">Loading…</div>;
  }

  return (
    <div className="report-page mx-auto max-w-2xl px-6 py-10 text-slate-200">
      <div className="report-no-print mb-6 flex justify-end">
        <button
          type="button"
          onClick={() => window.print()}
          className="rounded-md bg-sky-500 px-3 py-1.5 text-sm font-medium text-white hover:bg-sky-400"
        >
          Print / Save as PDF
        </button>
      </div>

      <header className="mb-6 border-b border-slate-700 pb-4">
        <p className="text-xs tracking-widest text-slate-500 uppercase">Helix score explainability report</p>
        <h1 className="mt-1 text-xl font-semibold">{lead.name}</h1>
        <p className="mt-1 text-sm text-slate-400">
          {lead.email} · {lead.source}
        </p>
        <p className="mt-1 text-xs text-slate-500">Generated {new Date().toLocaleString("en-US")}</p>
      </header>

      <section className="mb-6 flex flex-wrap gap-3 text-sm">
        <span className="font-semibold" style={{ color: tierColor(lead.tier) }}>
          {lead.score} · {lead.tier}
        </span>
        <span className="text-slate-400">{lead.classification}</span>
        <span className="text-slate-400">{Math.round(lead.confidence * 100)}% confidence</span>
        <span className="text-slate-400">{lead.engine} engine</span>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xs tracking-wide text-slate-500 uppercase">Why this score</h2>
        <p className="text-sm leading-relaxed text-slate-300">{lead.reasoning}</p>
      </section>

      {lead.fields.length > 0 ? (
        <section className="mb-6">
          <h2 className="mb-2 text-xs tracking-wide text-slate-500 uppercase">Field-by-field evidence</h2>
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-slate-700 text-left text-xs text-slate-500 uppercase">
                <th className="py-2 pr-3">Field</th>
                <th className="py-2 pr-3">Value</th>
                <th className="py-2 pr-3">Confidence</th>
                <th className="py-2">Evidence</th>
              </tr>
            </thead>
            <tbody>
              {lead.fields.map((field) => (
                <tr key={field.key} className="border-b border-slate-800 align-top">
                  <td className="py-2 pr-3 font-medium">{field.label}</td>
                  <td className="py-2 pr-3">{field.value}</td>
                  <td className="py-2 pr-3">{Math.round(field.confidence * 100)}%</td>
                  <td className="py-2">
                    {field.verified ? (
                      <span className="report-quote italic text-slate-400">&quot;{field.quote}&quot;</span>
                    ) : (
                      <span className="report-unverified text-amber-400">
                        no direct quote in source — engine confidence only
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ) : null}

      <footer className="mt-10 text-xs text-slate-600">
        Generated by Helix for Leads. Evidence marked with a quote is a literal excerpt from the
        lead&apos;s original message; unmarked fields reflect model/heuristic confidence without a
        directly quotable source.
      </footer>
    </div>
  );
}
