export {
  HELIX_HELP,
  INBOX_HELP,
  LEGAL_HELP,
  LEADS_HELP,
  COMMERCE_HELP,
  HOW_TO_USE_INBOX,
  HOW_TO_USE_LEGAL,
  HOW_TO_USE_LEADS,
  HOW_TO_USE_COMMERCE,
  TOUR_INBOX,
  TOUR_LEGAL,
  TOUR_LEADS,
  EMPTY_INBOX,
  EMPTY_LEGAL,
  EMPTY_LEADS,
  SHORTCUTS_INBOX,
  SHORTCUTS_LEGAL,
  SHORTCUTS_LEADS,
  tourDoneKey,
  type HelpSide,
  type HowToUseGuide,
  type HowToUseStep,
  type HowToUseShortcut,
  type TourStepDef,
  type EmptyStateCopy,
} from "./copy";
